name: Python Scheduled Script

on: 
  schedule:
  - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/requirements.txt"

      - name: Execute Python script
        run: python src/main.py

      - name: Commit files
        run: |
          git config --local user.name Piketulus
          git config --local user.email "joel.pietilainen@gmail.com"
          git add --all
          git commit -am "GH ACTION Healines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
